export { default as community } from "./community/community";
export { default as main } from "./main/main";
export { default as notifications } from "./notifications/Notifications";
export { default as profile } from "./profile/Profile";
export { default as profileCard } from "./profileCard/ProfileCard";
export { default as SignIn } from "./singIn/SignIn";
export { default as SignUp } from "./signUp/SignUp";
export { default as statistics } from "./statistics/Statistics";
export { default as welcome } from "../services/welcome/Welcome";
